export const clients_logo = [
    {
        img: "/1.png",
        name: "BitBrowser",
    },
    {
        img: "/2.png",
        name: "ClonBrowser",
    },
    {
        img: "/3.png",
        name: "MuLogin",
    },
    {
        img: "/4.png",
        name: "XLogin",
    },
    {
        img: "/5.png",
        name: "VMLogin",
    },
    {
        img: "/6.png",
        name: "Dolphin {anly}",
    },
    {
        img: "/7.png",
        name: "Accovod",
    },
    {
        img: "/8.png",
        name: "ixBrowser",
    },
    {
        img: "/9.png",
        name: "Linken Sphere",
    },
    {
        img: "/10.png",
        name: "IDENTORY",
    },
]
export const tariff_cards = [
    [
        {
            name: "Базовый",
            price: "5",
            perprice: "$2.6/ГБ",
            currency: "USD",
            description: "Подпишитесь на наш Telegram канал",
            features: [
                "Выбор страны/города",
                "Выбор провайдера",
                "24/7 поддержка",
                "Этические IP-адрес",
            ],
            button: "ПОДПИСАТЬСЯ",
            button_color: "black_btn",
        },
        {
            name: "Базовый",
            price: "5",
            perprice: "$2.6/ГБ",
            currency: "USD",
            features: [
                "Выбор страны/города",
                "Выбор провайдера",
                "24/7 поддержка",
                "Этические IP-адрес",
            ],
            button: "Купить",
            button_color: "black_btn",
        },
        {
            name: "Базовый",
            price: "5",
            perprice: "$2.6/ГБ",
            currency: "USD",

            features: [
                "Выбор страны/города",
                "Выбор провайдера",
                "24/7 поддержка",
                "Этические IP-адрес",
            ],
            button: "Купить",
            button_color: "black_btn",
        },
        {
            name: "Базовый",
            price: "5",
            perprice: "$2.6/ГБ",
            currency: "USD",
            features: [
                "Выбор страны/города",
                "Выбор провайдера",
                "24/7 поддержка",
                "Этические IP-адрес",
            ],
            button: "Купить",
            button_color: "black_btn",
        },
        {
            name: "Базовый",
            price: "5",
            perprice: "$2.6/ГБ",
            currency: "USD",

            features: [
                "Выбор страны/города",
                "Выбор провайдера",
                "24/7 поддержка",
                "Этические IP-адрес",
            ],
            button: "Купить",
            button_color: "black_btn",
        },
        {
            name: "Базовый",
            price: "5",
            perprice: "$2.6/ГБ",
            currency: "USD",
            features: [
                "Выбор страны/города",
                "Выбор провайдера",
                "24/7 поддержка",
                "Этические IP-адрес",
            ],
            button: "Купить",
            button_color: "black_btn",
        },
    ],
    [
        {
            name: "Базовый",
            price: "5",
            perprice: "$2.6/ГБ",
            currency: "USD",
            features: [
                "Выбор страны/города",
                "Выбор провайдера",
                "24/7 поддержка",
                "Этические IP-адрес",
            ],
            button: "Купить",
            button_color: "black_btn",
        },
    ],
    [
        {
            name: "Базовый",
            price: "5",
            perprice: "$2.6/ГБ",
            currency: "USD",
            features: [
                "Выбор страны/города",
                "Выбор провайдера",
                "24/7 поддержка",
                "Этические IP-адрес",
            ],
            button: "Купить",
            button_color: "black_btn",
        },
        {
            name: "Базовый",
            price: "5",
            perprice: "$2.6/ГБ",
            currency: "USD",
            features: [
                "Выбор страны/города",
                "Выбор провайдера",
                "24/7 поддержка",
                "Этические IP-адрес",
            ],
            button: "Купить",
            button_color: "black_btn",
        },
    ]

]
export const popular_usage = [
    {
        name: "popular_1",
        img: "/popular_images/1.svg",
    },
    {
        name: "popular_2",
        img: "/popular_images/2.svg",
    },
    {
        name: "popular_3",
        img: "/popular_images/3.svg",
    },
    {
        name: "popular_4",
        img: "/popular_images/4.svg",
    },
    {
        name: "popular_5",
        img: "/popular_images/5.svg",
    },
    {
        name: "popular_6",
        img: "/popular_images/6.svg",
    },
    {
        name: "popular_7",
        img: "/popular_images/7.svg",
    },
    {
        name: "popular_8",
        img: "/popular_images/8.svg",
    },
    {
        name: "popular_9",
        img: "/popular_images/9.svg",
    },
    {
        name: "popular_10",
        img: "/popular_images/10.svg",
    },

]
export const type_of_payment = [
    {
        title: "VISA, MasterCard, UnionPay, Мир",
        description: "by_bankcards",
        image: "/visa.png"
    },
    {
        title: "Bitcoin",
        description: "btc",
        image: "/btc.png"
    },
    {
        title: "faster_payments",
        description: "fps",
        image: "/system.png"
    },
    {
        title: "Ethereum",
        description: "eth",
        image: "/eth.png"
    },
    {
        title: "e_wallets",
        description: "yoomoney",
        image: "/yumoney.png"
    },
    {
        title: "Tether",
        description: "tether",
        image: "/tether.png"
    },
]
export const faq_examples = [
    {
        title: "Что означают резидентские прокси?",
        content:
            "Резидентские прокси (residential proxies) представляют собой IP-адреса, которые предоставляются интернет-провайдерами реальным пользователям домашних сетей. В отличие от данных центров обработки данных (Data Center Proxies), которые предоставляют IP-адреса, принадлежащие серверам в центрах обработки данных, резидентские прокси имитируют обычные домашние IP-адреса.",
    },
    {
        title: "Какие преимущества дают использования резидентских прокси?",
        content:
            "Использование резидентских прокси может предоставить несколько преимуществ в различных областях:  Аутентичность и Низкое Обнаружение:  Резидентские прокси предоставляют реальные IP-адреса, которые принадлежат домашним сетям реальных пользователей. Это делает их более аутентичными и менее подверженными обнаружению, чем прокси с центров обработки данных.  Эффективное Обход Блокировок: В сравнении с центрами обработки данных, резидентские прокси чаще обходят блокировки, так как их IP-адреса выглядят более обычными и не вызывают подозрений.",
    },
    {
        title: "Чем резидентские прокси отличаются от прокси дата-центров?",
        content:
            "Резидентские прокси и прокси дата-центров различаются по нескольким ключевым характеристикам, включая источник IP-адресов, аутентичность, уровень обнаружения, стоимость и применение. Вот основные различия между ними:",
    },
];

export const countries = [
    {
        ru: [
            "Северная Америка",
            "Ангилья",
            "Белиз",
            "Куба",
            "Гренада",
            "Ямайка",
            "Пуэрто-Рико",
            "Сен-Пьер и Микелон",
            "Антигуа и Барбуда",
            "Бермуды",
            "Кюрасао",
            "Гваделупа",
            "Мартиника",
            "Сен-Бартелеми",
            "Сент-Винсент и Гренадины",
            "Аруба",
            "Бонайре, Синт-Эстатиус и Саба",
            "Доминика",
            "Гватемала",
            "Мексика",
            "Сент-Китс и Невис",
            "Синт-Мартен",
            "Соединенные Штаты",
            "Багамские острова",
            "Британские Виргинские острова",
            "Каймановы острова",
            "Доминиканская Республика",
            "Гаити",
            "Никарагуа",
            "Сент-Люсия",
            "Тринидад и Тобаго",
            "Виргинские острова",
            "Барбадос",
            "Канада",
            "Коста-Рика",
            "Сальвадор",
            "Гондурас",
            "Панама",
            "Сен-Мартен",
            "Острова Теркс и Кайкос"
        ],
        en: [
            "North America",
            "Anguilla",
            "Belize",
            "Cuba",
            "Grenada",
            "Jamaica",
            "Puerto Rico",
            "Saint Pierre and Miquelon",
            "Antigua and Barbuda",
            "Bermuda",
            "Curaçao",
            "Guadeloupe",
            "Martinique",
            "Saint Barthélemy",
            "Saint Vincent and the Grenadines",
            "Aruba",
            "Bonaire, Sint Eustatius, and Saba",
            "Dominica",
            "Guatemala",
            "Mexico",
            "Saint Kitts and Nevis",
            "Sint Maarten",
            "United States",
            "Bahamas",
            "British Virgin Islands",
            "Cayman Islands",
            "Dominican Republic",
            "Haiti",
            "Nicaragua",
            "Saint Lucia",
            "Trinidad and Tobago",
            "Virgin Islands",
            "Barbados",
            "Canada",
            "Costa Rica",
            "El Salvador",
            "Honduras",
            "Panama",
            "Saint Martin",
            "Turks and Caicos Islands"
        ]
    },
    {
        ru: [
            "Южная Америка",
            "Аргентина",
            "Эквадор",
            "Парагвай",
            "Боливия",
            "Фаркландские острова",
            "Перу",
            "Бразилия",
            "Французская Гвиана",
            "Суринам",
            "Чили",
            "Гайана",
            "Уругвай",
            "Колумбия",
            "Монтсеррат"
        ],
        en: [
            "South America",
            "Argentina",
            "Ecuador",
            "Paraguay",
            "Bolivia",
            "Falkland Islands",
            "Peru",
            "Brazil",
            "French Guiana",
            "Suriname",
            "Chile",
            "Guyana",
            "Uruguay",
            "Colombia",
            "Montserrat"
        ]
    },
    {
        ru: [
            "Европа",
            "Аландские острова",
            "Бельгия",
            "Чехия",
            "Франция",
            "Гернси",
            "Италия",
            "Литва",
            "Монако",
            "Португалия",
            "Украина",
            "Албания",
            "Босния и Герцеговина",
            "Дания",
            "Германия",
            "Венгрия",
            "Джерси",
            "Люксембург",
            "Черногория",
            "Румыния",
            "Испания",
            "Великобритания",
            "Болгария",
            "Эстония",
            "Гибралтар",
            "Исландия",
            "Косово",
            "Македония",
            "Нидерланды",
            "Сан-Марино",
            "Швеция",
            "Ватикан",
            "Австрия",
            "Хорватия",
            "Фарерские острова",
            "Греция",
            "Ирландия",
            "Латвия",
            "Мальта",
            "Норвегия",
            "Сербия",
            "Швейцария",
            "Белоруссия",
            "Кипр",
            "Финляндия",
            "Гренландия",
            "Остров Мэн",
            "Лихтенштейн",
            "Молдавия",
            "Польша",
            "Словакия",
            "Турция"
        ],
        en: [
            "Europe",
            "Åland Islands",
            "Belgium",
            "Czech Republic",
            "France",
            "Guernsey",
            "Italy",
            "Lithuania",
            "Monaco",
            "Portugal",
            "Ukraine",
            "Albania",
            "Bosnia and Herzegovina",
            "Denmark",
            "Germany",
            "Hungary",
            "Jersey",
            "Luxembourg",
            "Montenegro",
            "Romania",
            "Spain",
            "United Kingdom",
            "Bulgaria",
            "Estonia",
            "Gibraltar",
            "Iceland",
            "Kosovo",
            "Macedonia",
            "Netherlands",
            "San Marino",
            "Sweden",
            "Vatican City",
            "Austria",
            "Croatia",
            "Faroe Islands",
            "Greece",
            "Ireland",
            "Latvia",
            "Malta",
            "Norway",
            "Serbia",
            "Switzerland",
            "Belarus",
            "Cyprus",
            "Finland",
            "Greenland",
            "Isle of Man",
            "Liechtenstein",
            "Moldova",
            "Poland",
            "Slovakia",
            "Turkey"
        ]

    },
    {
        ru: [
            "Азия и Ближний Восток",
            "Афганистан",
            "Бутан",
            "Гонконг",
            "Израиль",
            "Кыргызстан",
            "Мальдивы",
            "Оман",
            "Россия",
            "Объединенные Арабские Эмираты",
            "Армения",
            "Бруней",
            "Индия",
            "Лаос",
            "Монголия",
            "Саудовская Аравия",
            "Тайвань",
            "Узбекистан",
            "Азербайджан",
            "Камбоджа",
            "Индонезия",
            "Ливан",
            "Мьянма",
            "Палестинская территория",
            "Сингапур",
            "Таджикистан",
            "Вьетнам",
            "Бахрейн",
            "Китай",
            "Иран",
            "Казахстан",
            "Макао",
            "Непал",
            "Филиппины",
            "Южная Корея",
            "Таиланд",
            "Йемен",
            "Бангладеш",
            "Грузия",
            "Ирак",
            "Кувейт",
            "Малайзия",
            "Северная Корея",
            "Катар",
            "Шри-Ланка",
            "Туркменистан"
        ],
        en: [
            "Asia and the Middle East",
            "Afghanistan",
            "Bhutan",
            "Hong Kong",
            "Israel",
            "Kyrgyzstan",
            "Maldives",
            "Oman",
            "Russia",
            "United Arab Emirates",
            "Armenia",
            "Brunei",
            "India",
            "Laos",
            "Mongolia",
            "Saudi Arabia",
            "Taiwan",
            "Uzbekistan",
            "Azerbaijan",
            "Cambodia",
            "Indonesia",
            "Lebanon",
            "Myanmar",
            "Palestinian Territory",
            "Singapore",
            "Tajikistan",
            "Vietnam",
            "Bahrain",
            "China",
            "Iran",
            "Kazakhstan",
            "Macao",
            "Nepal",
            "Philippines",
            "South Korea",
            "Thailand",
            "Yemen",
            "Bangladesh",
            "Georgia",
            "Iraq",
            "Kuwait",
            "Malaysia",
            "North Korea",
            "Qatar",
            "Sri Lanka",
            "Turkmenistan"
        ]
    }
]


export const globalCn = [
    {
        name: "USA",
        sub: "11,074,560 IPs",
        img: "/usa.svg"
    },
    {
        name: "Germany",
        sub: "3,579,899 IPs",
        img: "/de.svg"
    },
    {
        name: "Russia",
        sub: "3,579,899 IPs",
        img: "/rus.svg"
    },
    {
        name: "UK",
        sub: "3,622,838 IPs",
        img: "/uk.svg"
    },
    {
        name: "Canada",
        sub: "4,074,560 IPs",
        img: "/can.svg"
    },
 
]